INSERT INTO tb_post(title, content, category, created_At, updated_At) VALUES ('My First Blog Post', 'This is the content of my first blog post.', 'Technology', NOW(), NOW())
INSERT INTO tb_post(title, content, category, created_At, updated_At) VALUES ('My Second Blog Post', 'This is the content of my second blog post.', 'Technology', NOW(), NOW())
INSERT INTO tb_post(title, content, category, created_At, updated_At) VALUES ('My Third Blog Post', 'This is the content of my third blog post.', 'Health', NOW(), NOW())
INSERT INTO tb_post(title, content, category, created_At, updated_At) VALUES ('The health benefits of sleep', 'The benefits of sleep are...', 'Health', NOW(), NOW())
INSERT INTO tb_post(title, content, category, created_At, updated_At) VALUES ('Books to read this year', 'This year I will read...', 'Reading', NOW(), NOW())
INSERT INTO tb_post(title, content, category, created_At, updated_At) VALUES ('Exercise your body', 'Gym, running, martial arts...', 'Health', NOW(), NOW())

INSERT INTO tb_post_tags(post_id, tag_name) VALUES (1, 'Tech')
INSERT INTO tb_post_tags(post_id, tag_name) VALUES (1, 'Programming')
INSERT INTO tb_post_tags(post_id, tag_name) VALUES (2, 'Tech')
INSERT INTO tb_post_tags(post_id, tag_name) VALUES (2, 'Programming')
INSERT INTO tb_post_tags(post_id, tag_name) VALUES (3, 'Sleep')
INSERT INTO tb_post_tags(post_id, tag_name) VALUES (3, 'Exercise')
INSERT INTO tb_post_tags(post_id, tag_name) VALUES (4, 'Books')